steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - 'gcr.io/${PROJECT_ID}/olachill:${BUILD_ID}'
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${PROJECT_ID}/olachill:${BUILD_ID}'

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '$_SERVICE'
      - --image
      - 'gcr.io/${PROJECT_ID}/olachill:${BUILD_ID}'
      - --region
      - '$_REGION'
      - --platform
      - managed
      - --allow-unauthenticated
      - --quiet

images:
  - 'gcr.io/${PROJECT_ID}/olachill:${BUILD_ID}'

timeout: '1200s'

substitutions:
  _REGION: us-west1
  _SERVICE: olachill-chuy-n-gia-du-l-ch-nh-t-b-n
